imports:
- path: install.jinja

resources:
- name: install
  type: install.jinja
  properties:
    zone: europe-west1-b
    machineType: n1-standard-1

outputs:
- name: url
  value: http://$(ref.install.ip)
